// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWhJkPZB-odlMpqs6Vgj-EgSA1x9lf1zg',
    appId: '1:390710604198:web:d4d9fd82181b228eaf5f67',
    messagingSenderId: '390710604198',
    projectId: 'property-restart',
    authDomain: 'property-restart.firebaseapp.com',
    storageBucket: 'property-restart.appspot.com',
    measurementId: 'G-D9V249YF07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZpFtfM0b9lRoMkKobM9QxtK6_TRwjeHo',
    appId: '1:390710604198:android:b6e16602a1c966e8af5f67',
    messagingSenderId: '390710604198',
    projectId: 'property-restart',
    storageBucket: 'property-restart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-pNmhWufsX_SlqOrW-ZKOWk_erG1tE0k',
    appId: '1:390710604198:ios:678995f0bfe7f6cdaf5f67',
    messagingSenderId: '390710604198',
    projectId: 'property-restart',
    storageBucket: 'property-restart.appspot.com',
    androidClientId: '390710604198-7f5cu9bn31pm95sd1vech6r7c9bghfn4.apps.googleusercontent.com',
    iosClientId: '390710604198-la8aa4ip0sqg51q2j3doc9po138rpiuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );
}
